# Generated by Django 2.1.1 on 2018-11-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('delivery_address', models.TextField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True)),
                ('payment_method', models.CharField(choices=[('CH', 'Cash'), ('CD', 'Card')], max_length=20)),
                ('order_status', models.CharField(choices=[('CF', 'Confirmed'), ('R', 'Ready'), ('S', 'Send'), ('D', 'Delivered'), ('R', 'Returned'), ('C', 'Cancelled')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
                ('product', models.ManyToManyField(to='main.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Pizzeria'), ('S', 'Sushi-Bar')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('info', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurants'),
        ),
        migrations.AddField(
            model_name='food',
            name='pizza_sushi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PizzaSushi'),
        ),
    ]
